/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ClsContacto;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author JoalfeorAST
 */
public class FrmContacto extends javax.swing.JFrame {

    /**
     * Creates new form FrmContacto
     */
    public FrmContacto() {
        initComponents();
        this.setLocationRelativeTo(this);    
    }
    
    //Creamos el objeto para conectar el formulario con la clase
    ClsContacto contacto = new ClsContacto();
    
    //método para validar las cajas de texto y llama al método guardar
    public void validar() {
        if (txtnom_con.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Falto digitar el nombre");
            txtnom_con.grabFocus();

        } else if (txttel_con.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Falto digitar el telefono");
            txttel_con.grabFocus();

        } else if (txtema_con.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Falto digitar el email");
            txtema_con.grabFocus();

        } else if (txtasu_con.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Falto digitar el asunto");
            txtasu_con.grabFocus();

        } else if (txtmen_con.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Falto digitar el mensaje");
            txtmen_con.grabFocus();

        } else {
            this.captura();
            contacto.guardar();
        }
    }    

    public void captura() {
            contacto.setNom_con(txtnom_con.getText());
            contacto.setTel_con(Integer.parseInt(txttel_con.getText()));            
            contacto.setEma_con(txtema_con.getText());
            contacto.setAsu_con(txtasu_con.getText());
            contacto.setMen_con(txtmen_con.getText());
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtema_con = new javax.swing.JTextField();
        txttel_con = new javax.swing.JTextField();
        txtnom_con = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnlimpiar = new javax.swing.JButton();
        btnenviar = new javax.swing.JButton();
        txtasu_con = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmen_con = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btncomprobar1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(314, 424));
        setMinimumSize(new java.awt.Dimension(314, 424));
        setPreferredSize(new java.awt.Dimension(314, 424));
        setResizable(false);
        setSize(new java.awt.Dimension(314, 424));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 29)); // NOI18N
        jLabel6.setText("CONTACTO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("    Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("     Telefono  ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 80, 20));

        txtema_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtema_conActionPerformed(evt);
            }
        });
        getContentPane().add(txtema_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, -1));

        txttel_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttel_conActionPerformed(evt);
            }
        });
        txttel_con.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttel_conKeyPressed(evt);
            }
        });
        getContentPane().add(txttel_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 180, -1));

        txtnom_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnom_conActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 180, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("     Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("   Asunto");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, 20));

        btnlimpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 90, 30));

        btnenviar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnenviar.setText("Enviar");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnenviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 90, 30));

        txtasu_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtasu_conActionPerformed(evt);
            }
        });
        txtasu_con.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtasu_conKeyPressed(evt);
            }
        });
        getContentPane().add(txtasu_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, -1));

        txtmen_con.setColumns(20);
        txtmen_con.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtmen_con.setRows(5);
        txtmen_con.setBorder(null);
        jScrollPane1.setViewportView(txtmen_con);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 180, 140));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("  Mensaje");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, 20));

        btncomprobar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncomprobar1.setText("Volver");
        btncomprobar1.setMaximumSize(new java.awt.Dimension(79, 23));
        btncomprobar1.setMinimumSize(new java.awt.Dimension(79, 23));
        btncomprobar1.setPreferredSize(new java.awt.Dimension(79, 23));
        btncomprobar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprobar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btncomprobar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 420));

        getAccessibleContext().setAccessibleName("Contacto");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtema_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtema_conActionPerformed

    }//GEN-LAST:event_txtema_conActionPerformed

    private void txttel_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttel_conActionPerformed

    }//GEN-LAST:event_txttel_conActionPerformed

    private void txtnom_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnom_conActionPerformed

    }//GEN-LAST:event_txtnom_conActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        
        //limpiar campos
        txtnom_con.setText("");
        txtema_con.setText("");
        txttel_con.setText("");
        txtasu_con.setText("");
        txtmen_con.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        
        //llamamos el metodo validar      
        this.validar();
        
        //limpiar campos
        txtnom_con.setText("");
        txtema_con.setText("");
        txttel_con.setText("");
        txtasu_con.setText("");
        txtmen_con.setText("");
    }//GEN-LAST:event_btnenviarActionPerformed

    private void txtasu_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtasu_conActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtasu_conActionPerformed

    private void txtasu_conKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtasu_conKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtasu_conKeyPressed

    private void txttel_conKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttel_conKeyPressed
        
//Validar para que solo reciba numeros
        txttel_con.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_txttel_conKeyPressed

    private void btncomprobar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprobar1ActionPerformed
        FrmCliente obj=new FrmCliente();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btncomprobar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncomprobar1;
    private javax.swing.JButton btnenviar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtasu_con;
    private javax.swing.JTextField txtema_con;
    private javax.swing.JTextArea txtmen_con;
    private javax.swing.JTextField txtnom_con;
    private javax.swing.JTextField txttel_con;
    // End of variables declaration//GEN-END:variables
}
